---
- name: install and configure development tools
  hosts: localhost
  vars:
    mac_config_apps:
      - gcc
      - llvm
      - pgadmin4
      - podman
      - cmake
      - jq
      - aws-sam-cli
      - awscli
      - aws-cdk
      - ripgrep
  tasks:
    - name: install nodejs, podman, python, psql
      community.general.homebrew:
        state: present
        name: "{{mac_config_apps}}"
