---
- name: install fixes for Mac annoyances
  hosts: localhost
  vars:
    mac_config_fix_apps:
      - rectangle
      - maccy
      - macfuse
  tasks:
    - name: install apps to improve QoL
      community.general.homebrew:
        state: present
        name: "{{mac_config_fix_apps}}"

    - name: fix the default location for screenshots
      shell: "defaults write com.apple.screencapture location {{ansible_env.HOME}}/Documents/workshop/screenshots"
